### ISSUE TITLE
: Could not load 'plugins\ItemBlacklist-1.4.0.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by DahunDev** [DoubleDoorDevelopment/ItemBlacklist#23]
[21:04:10] [Server thread/ERROR]: Could not load 'plugins\ItemBlacklist-1.4.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[craftbukkit.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more

**Comment by Claycorp** [comment]
This is a FORGE MOD.
This is not a BUKKIT PLUGIN.
